Add documentation for retrieving Aviary webhooks
phylum-dev/documentation pull request #221
Opened 2024-10-09 21:02 UTC by cd-work

This documents the `GET /webhooks` endpoint of Aviary and also adds missing warnings about persisting the token into the shell history where relevant.

2024-10-09 21:28 UTC, maxrake requested changes
Review for content/format is complete and there is one typo to correct. I tried following the directions in the docs and could not get my configured webhooks to show with the command as listed. Has it been tested?

2024-10-09 21:28 UTC, maxrake commented on docs/artifact_repositories/api.md
> +### Retreiving configured Webhooks
```suggestion
### Retrieving configured Webhooks
```

2024-10-09 22:11 UTC, maxrake commented
> It's not in prod yet. We can in theory wait on prod but it was so simple I thought it wouldn't be necessary. I don't mind just holding this PR open either though.

Ah...that explains it. I could go either way on syncing (or not) this change with a PROD release.

2024-10-09 22:12 UTC, cd-work commented
> Ah...that explains it. I could go either way on syncing (or not) this change with a PROD release.

Let's just wait and get another prod release out for aviary asap. Shouldn't be that difficult.

2024-10-09 22:15 UTC, maxrake approved these changes
LGTM

2024-10-09 22:17 UTC, cd-work commented
Decided to just push a new aviary release so we can get this properly tested by a second party: https://github.com/phylum-dev/aviary/pull/72.

2024-10-10 20:13 UTC, maxrake commented
The changes have been tested and confirmed to work now that they exist in PROD.

2024-10-10 20:18 UTC, merged